apiVersion: apps/v1
kind: Deployment
metadata:
  name: openobserve
  labels:
    app: openobserve
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: openobserve
  template:
    metadata:
      labels:
        app: openobserve
    spec:
      containers:
        - name: openobserve
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5080
          env:
            - name: ZO_ROOT_USER_EMAIL
              value: "admin@example.com"
            - name: ZO_ROOT_USER_PASSWORD
              value: "supersecurepassword"
