apiVersion: v1
kind: Service
metadata:
  name: openobserve
spec:
  selector:
    app: openobserve
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5080
      nodePort: {{ .Values.service.nodePort }}
