service:
  type: ClusterIP

rbac:
  create: true

serviceAccount:
  create: true

input:
  tail:
    enabled: true
    path: "/var/log/containers/*.log"
    parser: docker
    refresh_interval: 5
    mem_buf_limit: 5MB
    skip_long_lines: On

filter:
  kubernetes:
    enabled: true
    mergeLog: true
    mergeLogKey: log_processed
    keepLog: true
    labels: true
    annotations: true
    extraMetadata: true
    extraMetadataFields:
      - container_name
      - namespace_name
      - pod_name

outputs:
  http:
    enabled: true
    host: openobserve.openobserve-test-new-1.svc.cluster.local
    port: 5080
    uri: "/api/default/_ingest"
    header:
      ZO-USER: "admin@example.com"
      ZO-PASSWORD: "supersecurepassword"
