apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-app
  labels:
    app: logging-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging-app
  template:
    metadata:
      labels:
        app: logging-app
    spec:
      containers:
      - name: logger
        image: busybox
        command: ['sh', '-c', 'while true; do echo "{\"level\":\"INFO\",\"message\":\"Hello from logging app\"}"; sleep 5; done']
