apiVersion: apps/v1
kind: Deployment
metadata:
  name: openobserve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openobserve
  template:
    metadata:
      labels:
        app: openobserve
    spec:
      containers:
        - name: openobserve
          image: public.ecr.aws/zinclabs/openobserve:v0.15.0-rc2
          ports:
            - containerPort: 5080
          env:
            - name: ZO_ROOT_USER_EMAIL
              value: "admin@example.com"
            - name: ZO_ROOT_USER_PASSWORD
              value: "changeme"
---
apiVersion: v1
kind: Service
metadata:
  name: openobserve
spec:
  type: NodePort
  selector:
    app: openobserve
  ports:
    - port: 5080
      targetPort: 5080
      nodePort: 30081
