apiVersion: apps/v1
kind: Deployment
metadata:
  name: openobserve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openobserve
  template:
    metadata:
      labels:
        app: openobserve
    spec:
      containers:
      - name: openobserve
        image: public.ecr.aws/zinclabs/openobserve:latest
        ports:
        - containerPort: 5080
---
apiVersion: v1
kind: Service
metadata:
  name: openobserve
spec:
  type: NodePort
  selector:
    app: openobserve
  ports:
  - port: 5080
    targetPort: 5080
    nodePort: 30081
